services:
  db:
    image: mysql:8.0
    container_name: salesapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salesdb
      MYSQL_USER: salesdb
      MYSQL_PASSWORD: salesdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sales-app-api-network

volumes:
  db_data:

networks:
  sales-app-api-network:
    external: true
